spring:
  application:
    name: account
  h2:
#  profiles:
#    active: "prod"
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
      show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"   # optional -> instruct running spring application,
                                                             # even if error configuring the configuration property

management:
  endpoints:
    web:
      exposure:
        include: "*"


rabbitmq:
  host: "localhost"
  port: 5672
  username: "guest"
  password: "guest"


server:
  port: 8080